export const WEB3_TYPES = {
  WEB3_LOADING: "WEB3_LOADING",
  WEB3_LOADED: "WEB3_LOADED",
  WEB3_ERROR: "WEB3_ERROR",
  WEB3_ACCOUNT_LOADED: "WEB3_ACCOUNT_LOADED",
  WEB3_ACCOUNT_DISCONNECT: "WEB3_ACCOUNT_DISCONNECT",
};
