export const TOKEN_ACTION_TYPES = {
  TOKEN_LOADED: "TOKEN_LOADED",
  TOKEN_LOADING_ERROR: "TOKEN_LOADING_ERROR",
  TOKEN_BALANCE_LOADED: "TOKEN_BALANCE_LOADED",
  TOKEN_APPROVAL_LOADING: "TOKEN_APPROVAL_LOADING",
  TOKEN_APPROVED: "TOKEN_APPROVED",
  TOKEN_APPROVAL_ERROR: "TOKEN_APPROVAL_ERROR",
  TOKEN_RESET: "TOKEN_RESET",
};
