export const FARMING_ACTION_TYPES = {
  FARMING_CONTRACT_LOADING: "FARMING_CONTRACT_LOADING",
  FARMING_CONTRACT_LOADED: "FARMING_CONTRACT_LOADED",
  FARMING_CONTRACT_ERROR: "FARMING_CONTRACT_ERROR",
};
