export const LPTOKEN_ACTION_TYPES = {
  LPTOKEN_CONTRACT_LOADING: "LPTOKEN_CONTRACT_LOADING",
  LPTOKEN_CONTRACT_LOADED: "LPTOKEN_CONTRACT_LOADED",
  LPTOKEN_CONTRACT_ERROR: "LPTOKEN_CONTRACT_ERROR",
  LPTOKEN_APPROVED: "LPTOKEN_APPROVED",
  LPTOKEN_APPROVAL_LOADING: "LPTOKEN_APPROVAL_LOADING",
  LPTOKEN_APPROVAL_ERROR: "LPTOKEN_APPROVAL_ERROR",
  LPTOKEN_LOAD_BALANCE: "LPTOKEN_LOAD_BALANCE",
  LPTOKEN_RESET: "LPTOKEN_RESET",
};
