export const USER_DEPOSIT_ACTION_TYPES = {
  USER_DEPOSIT_DETAILS_FETCHED: "USER_DEPOSIT_DETAILS_FETCHED",
  USER_DEPOSIT_DETAILS_LOADING: "USER_DEPOSIT_DETAILS_LOADING",
  USER_DEPOSIT_DETAILS_ERROR: "USER_DEPOSIT_DETAILS_ERROR",
  USER_DEPOSIT_DETAILS_RESET: "USER_DEPOSIT_DETAILS_RESET",
};
