export const FARMING_USERDEPOSIT_ACTION_TYPES = {
  FARMING_USERDEPOSIT_FETCHING: "FARMING_USERDEPOSIT_FETCHING",
  FARMING_USERDEPOSIT_FETCHED: "FARMING_USERDEPOSIT_FETCHED",
  FARMING_USERDEPOSIT_ERROR: "FARMING_USERDEPOSIT_ERROR",
  FARMING_USERDEPOSIT_RESET: "FARMING_USERDEPOSIT_RESET",
};
